### your site title here

title: L'Ann√©e de L'album
description: '12 mois, 12 chansons.'
author: Floby

#baseurl: /bidule
locale: fr
lang: fr
language: fr

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md



# Tracker
analytics: UA-37756010-2

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md


gems: 
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
